#!/usr/bin/env bash

export SOURCE_="https://obsproject.com/wiki/install-instructions#linux"

export TITLE_=${0##*/}
./meta/installingHeader


sudo -y add-apt-repository ppa:obsproject/obs-studio
sudo apt update

sudo -y apt install ffmpeg v4l2loopback-dkms obs-studio
