#!/usr/bin/env bash

export SOURCE_="none"
export TITLE_=${0##*/}
./meta/installingHeader

sudo apt -y install terminator

echo "Terminator: Remember to set 'Run command as a login shell'." >> $END_MSG_FILE
