#!/usr/bin/env bash

export SOURCE_="https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH"
export export TITLE_=${0##*/}

./meta/installingHeader

sudo apt -y install zsh

# copy zsh configs

for f in ./src/zsh/*; do
  bash "$f" 
done

cp ./files/.zshrc ~/

