#!/usr/bin/env bash

export SOURCE_="https://github.com/TheAssassin/AppImageLauncher"

export TITLE_=${0##*/}
./meta/installingHeader

sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install appimagelauncher
mkdir ~/Applications

