#!/usr/bin/env bash

SOURCE_="https://github.com/TheAssassin/AppImageLauncher"

./meta/installingHeader $SOURCE_ ${0##*/}

sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install appimagelauncher
mkdir ~/Applications

