#!/usr/bin/env bash

export SOURCE_="https://github.com/nvm-sh/nvm#installing-and-updating"
export TITLE_=${0##*/}
./meta/installingHeader

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

echo "Check .zshrc .bashrc .profile .bash_profile for nvm export."

nvm install --lts

