#!/usr/bin/env bash

SOURCE_="https://rvm.io/"
TITLE_="rvm via poor-mans-rails-installer"

./meta/installingHeader $SOURCE_ $TITLE_

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable --rails

echo "Reboot Your Terminal After Installation"

# install the package and set up configs

