#!/usr/bin/env bash

export SOURCE_="none"

DOWNLOAD_="https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-linux-x86_64.AppImage"

export TITLE_=${0##*/}
./meta/installingHeader

./meta/installAppImage $DOWNLOAD_