#!/usr/bin/env bash

SOURCE_="https://github.com/ohmyzsh/ohmyzsh"
./meta/installingHeader $SOURCE_ ${0##*/}

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# copy configs and things
