#!/usr/bin/env bash

export SOURCE_="https://github.com/ohmyzsh/ohmyzsh"
export TITLE_=${0##*/}
./meta/installingHeader

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# copy configs and things
