#!/usr/bin/env bash

export SOURCE_="https://github.com/TheAssassin/AppImageLauncher"

export TITLE_=${0##*/}
./meta/installingHeader

sudo -y add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo -y apt install appimagelauncher
mkdir ~/Applications

for f in ./src/appimage/*; do
  bash "$f" 
done

