#!/usr/bin/env bash

export SOURCE_="https://github.com/nvm-sh/nvm#installing-and-updating"
export TITLE_=${0##*/}
./meta/installingHeader

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash


echo "NVM: Check the rc files(.zshrc .bashrc .profile .bash_profile) for the nvm export." >> $END_MSG_FILE

export ~/.bashrc
export ~/.zshrc

nvm install --lts

