#!/usr/bin/env bash

export SOURCE_="https://rvm.io/"
export TITLE_="rvm via poor-mans-rails-installer"

./meta/installingHeader $export SOURCE_ $TITLE_

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable --rails

echo "RVM: Remember to set 'Run command as a login shell' in your terminal." >> $END_MSG_FILE
echo "RVM: And reboot Your Terminal" >> $END_MSG_FILE

source /home/sean/.rvm/scripts/rvm

# install the package and set up configs

