#!/usr/bin/env bash

export SOURCE_="https://obsproject.com/wiki/install-instructions#linux"

export TITLE_=${0##*/}
./meta/installingHeader


sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update

sudo apt install ffmpeg v4l2loopback-dkms obs-studio
